# _config.yml

# Site Settings
title: StudentGuide
description: A collection of user guides by Octupus.
remote_theme: just-the-docs/just-the-docs
url: "https://itshaihong.github.io/StudentGuide" # The base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Optional: Set a permalink style
permalink: /:title/
